# -*- coding: utf-8 -*-
"""PLOTAQEU.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F1Rz1qnP9nZCz3a2aCH6a3j5hs4mfBsm
"""


import pandas as pd
import streamlit as st
import plotly.express as px



# Read the CSV file directly from the GitHub URL
url = 'https://raw.githubusercontent.com/JesHP73/plotAQEU/78dd92e3c98710a024cb332c6b753fd99aceac64/plot_aqi_df.csv'
plot_aqi_df = pd.read_csv(url)

# Calculate the mean AQI per year for each country
mean_aqi_per_country = plot_aqi_df.groupby(['year', 'country'])['AQI'].mean().reset_index()
mean_aqi_per_country['year'] = pd.to_datetime(mean_aqi_per_country['year'], format='%Y')

# List of all countries
all_countries = mean_aqi_per_country['country'].unique().tolist()

# Streamlit app
st.title('Air Quality Index 1990-2023')

# Dropdown for country selection
selected_countries = st.multiselect("Select country:", options=all_countries, default=all_countries)

# Function to create the figure
def create_figure(selected_countries):
    if 'All' in selected_countries or not selected_countries:
        filtered_data = mean_aqi_per_country.groupby('year')['AQI'].mean().reset_index()
        filtered_data['country'] = 'All Countries'
    else:
        filtered_data = mean_aqi_per_country[mean_aqi_per_country['country'].isin(selected_countries)]

    fig = px.line(filtered_data, x='year', y='AQI', color='country',
                  title='Average EU AQI per Year by Selected Country(s)')
    fig.update_layout(plot_bgcolor='white', paper_bgcolor='white')
    return fig

# Display the plot
st.plotly_chart(create_figure(selected_countries))
